- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/FinishPreparationDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
1. feat::약속 준비 종료 이후 관련값 업데이트 기능 구현
- PUT /user/{userId}/finish-preparation
- 클라이언트에서 약속이 종료됐을 때 본 API 호출
- 지각시간(Schedule테이블)과 성실도점수(User테이블)가 업데이트됨.
2. feat:: 유저 회원가입시 성실도 관련 속성 초기화
- 회원가입시 성실도점수는 -1, 초기화이후약속수는 0, 초기화이후지각수는 0으로 초기화되게 만듦(기존에는 전부 NULL로 초기화 돼서 성실도 점수 업데이트하는 과정에서 오류 발생했음.)
> [Feat] 성실도 관련 기능 구현

- ontime-back/src/main/java/devkor/ontime_back/repository/UserRepository.java
- ontime-back/src/main/java/devkor/ontime_back/repository/UserSettingRepository.java
- ontime-back/src/main/java/devkor/ontime_back/service/NotificationService.java
약속알림 스케줄러의 서비스 레이어에서 알림 보내기 전에
약속을 바탕으로 사용자 조회를 조회하고, 사용자를 바탕으로 사용자 세팅을 조회해
알림 허용여부를 확인한 뒤 알림 보내도록 로직 수정함.
> [mod] 사용자 알림 미허용 시 약속알림 가지 않도록 스케줄러 로직 수정

- ontime-back/src/main/java/devkor/ontime_back/controller/PreparationController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationService.java
- 약속 종료 이후 지각시간, 성실도 점수 초기화 이후 약속 수, 성실도 점수 초기화 이후 지각 수, 성실도 점수가 반드시 모두 업데이트 되어야 데이터 정합성이 지켜져 트랜잭션 처리하였음.
- 기존 약속 준비 종료 이후 속성 업데이트하는 API는 컨트롤러에서 지각시간 업데이트, 성실도 점수 업데이트하는 메서드를 서비스 계층에서 각각 호출함
- 컨트롤러에서 서비스 계층의 하나의 메서드만 호출하게 만들어 서비스 계층에서 해당 메서드 트랙잭션 처리하도록 로직 수정
- PreparationController로 API를 따로 뺐음.(기존엔 UserController에 있었음)
- PreparationService에 finishPreparation 메서드 정의해서 트랜잭션 처리해두었음.
> [mod] 약속 준비 종료 이후 속성 업데이트 API 트랜잭션 처리

- ontime-back/src/main/java/devkor/ontime_back/dto/ChangePasswordDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserAdditionalInfoDto.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- ontime-back/src/test/java/devkor/ontime_back/ControllerTestSupport.java
- ontime-back/src/test/java/devkor/ontime_back/TestSecurityConfig.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserAuthControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/global/generallogin/filter/CustomJsonUsernamePasswordAuthenticationFilterTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/UserAuthServiceTest.java
- 추가정보 기입 API 컨트롤러, 서비스 계층 테스트코드 작성 완료
- 비밀번호 변경 API 컨트롤러, 서비스 계층 테스트코드 작성 완료
- 계정 삭제 API 컨트롤러, 서비스 계층 테스트코드 작성 완료
- 일반로그인 테스트는 설계 및 작성 비용이 많이 들어 패스하였음. 
로그인은 수동테스트 하여야함.
- 모든 API에 대한 비인증 테스트를 위해 TestSecurityConfig파일을 테스트
디렉토리에 만들었고, 인증부분에 permitAll()코드를 삽입해 jwt인증
없이도 API요청이 가능케 하였음.
- 테스트 코드를 작성하는 와중에 프로덕션 코드의 리팩토링도 진행하였음
(트랜잭션으로 인한 성능 감소를 방지하기 위해 UserAuthService 클래스의 상단에 @transaction(readOnly = True)를 걸고
내부에 CUD작업이 필요한 메소드에 @transaction을 추가로 걸었음.)
> [test] UserAuthController 테스트코드 작성 완료

- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdateSpareTimeDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
- ontime-back/src/test/java/devkor/ontime_back/ControllerTestSupport.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserAuthControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/UserAuthServiceTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/UserServiceTest.java
- **성실도점수 조회 API** 컨트롤러, 서비스 계층 테스트코드 작성 완료
- **성실도점수 초기화 API** 컨트롤러, 서비스 계층 테스트코드 작성 완료
- **성실도점수 업데이트 API** 컨트롤러, 서비스 계층 테스트코드 작성 완료
- **여유시간 업데이트 API** 컨트롤러, 서비스 계층 테스트코드 작성 완료
- 테스트 코드를 작성하는 도중 **프로덕션 코드의 리팩토링**도 진행하였음
(유저 엔티티의 PunctualityScore, ScheduleCountAfterReset, LatenessCountAfterRest의 
**@Setter 제거**하고 Set메서드를 엔티티 안에 만듦)
- **테스트코드에서 빌더패턴으로 하드저장한 객체**는 **영속성 컨텍스트**에 들어가지 않으므로 테스트코드에서 해당 객체의 값의 변경을 확인하고 싶으면 findbyId등의 메서드를 통해 **영속성 컨텍스트에서 관리되는 객체의 복사본**으로 값의 변경을 확인해야한다. 
(하드저장한 객체에서 getId() 등을 하면 업데이트된 값이 아니라 기존 하드 저장한 값이 반환됨.)
- 테스트코드 예외발생시 userId = 2L로 하드코딩하니까 **동시성문제** 발생했음. 한 메서드만 독립적으로 수행했을 때 id가 2L인 데이터는 없어야하는데 실제로 클래스 단위로 테스트를 수행하니 id가 2L인 데이터가 존재하는 문제가 발생했음. **클래스의 각 테스트메서드가 병렬로 실행되다보니 생긴 문제**로 보임. (userId = 100L로 설정하니까 다 동작했음)
아마 teardown말고 @Transaction을 사용하면 이 문제가 방지될 …
> [test] 사용자 관련 코드(UserController, UserService) 테스트 작성 완료

- ontime-back/src/main/java/devkor/ontime_back/controller/FriendShipController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/CreateFriendshipLinkResponse.java
- ontime-back/src/main/java/devkor/ontime_back/dto/FriendDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/GetFriendshipRequesterResponse.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdateAcceptStatusDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/GetFriendListResponse.java
- ontime-back/src/main/java/devkor/ontime_back/service/FriendshipService.java
- ontime-back/src/test/java/devkor/ontime_back/ControllerTestSupport.java
- ontime-back/src/test/java/devkor/ontime_back/controller/FriendShipControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/FriendshipServiceTest.java
- **친구 추가 링크 생성 및 반환 API** 컨트롤러 계층 코드 및 테스트 코드 작성 완료
- **친구 추가 페이지 반환 API** 컨트롤러 계층 코드 및 테스트 코드 작성 완료
- **친구추가 수락상태 업데이트 API** 컨트롤러 계층 코드 및 테스트 코드 작성 완료
- **친구목록 조회 API** 컨트롤러 계층 코드 및 테스트 코드 작성 완료
- 위 모든 API에 대해 **Swagger API 명세** 완료
- **TDD(Test Driven Development)** 개발 방식으로 코드 작성하여 테스트 코드를 먼저 작성하고 프로덕션 코드를 작성해(RED-GREEN-REFACTOR) **엣지 케이스**를 충분히 고려하여 작성하였음.
- 친구 추가 링크를 통해 친구추가 하는 방식에는 아래의 두 가지 방법이 있으나 **일단은 1번 방식으로 구현**하였음. 친구 추가 링크 생성 및 반환 API를 통해 반환받은 UUID로 FE에서 링크를 구성하고 복사를 하면, 해당 링크는 친구 추가를 하려는 대상 1명에게만 유효함. 누군가 해당 링크를 클릭하면 그 링크는 더 이상 사용할 수 없게 됨.
> 1. 친구추가 하고자하는 대상 1명에게만 사용 가능
> 2. 친구추가 하고자하는 대상 여러명에게 사용 가능
- 차후 기획단에서 2번 방식을 명확히 요구하면 코드 수정이 필요해보임
- API 명세서의 **2. 친구 추가 페이지 반환 API**는 GET메소드를 사용하는데, 비즈니스레이어에서 데이터를 변경함. 이 부분 차후 리팩토링이 필요해보임.
- 링크 복사 외에 **카카오톡으로 바로 초대** 기능도 구현해야 함
- 친구관계를 …
> [feat] TDD개발방식으로 친구추가 관련 API들 컨트롤러 계층 코드 및 테스트 코드 작성 완료, Swagger 명세 완료

- ontime-back/src/main/java/devkor/ontime_back/controller/PreparationUserController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserOnboardingDto.java
- ontime-back/src/main/java/devkor/ontime_back/global/generallogin/handler/LoginSuccessHandler.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
- 회원가입 API에서 자동로그인 처리 및 role을 GUEST로 설정하도록 코드를 수정함.
회원가입 API를 호출하면, 회원가입이 되고 role을 GUEST로 설정한 뒤, JWT토큰을 헤더에 담아 반환함. 
사용자의 role이 GUEST인 것의 의미는 해당 사용자가 온보딩이 진행되지 않은 사용자라는 뜻임.
- 로그인할 때마다 role을 반환하도록 로그인API(정확히는 스프링시큐리티의 로그인필터)를 수정함.
로그인시 반환role값이 GUEST이면 FE에서 온보딩 API를 호출해 온보딩을 진행해야 함.
- 추가정보기입API와 첫준비과정세팅API를 온보딩API로 합쳤음.
온보딩API를 호출하면 추가정보가 기입되고, 디폴트 준비과정이 세팅되며 role이 USER로 업데이트됨.(온보딩이 완료됐다는 의미)
온보딩API에서는 토큰으로 사용자 인증이 필요함.
- **해피케이스**: 회원가입후 발급된 토큰으로 온보딩API를 호출해 온보딩을 완료하면 role이 USER(온보딩 완료)로 변경됨.
- **엣지케이스**: 회원가입만 하고 앱을 종료한 사용자는 앱을 다시 실행시키면 로그인을 해야함. 이때 로그인을 하면 role값으로 GUEST가 반환될 것임. FE에서는 로그인의 반환role값이 GUEST임을 확인하면 온보딩API를 호출해 해당 사용자의 온보딩을 진행시켜야함.
> [Hotfix] 온보딩 관련 API 대거 수정

- ontime-back/src/main/java/devkor/ontime_back/dto/PreparationDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserOnboardingDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Feedback.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/entity/UserSetting.java
- ontime-back/src/main/java/devkor/ontime_back/repository/FriendshipRepository.java
- ontime-back/src/main/java/devkor/ontime_back/repository/ScheduleRepository.java
- ontime-back/src/main/java/devkor/ontime_back/repository/UserSettingRepository.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserAuthControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/UserAuthServiceTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/UserServiceTest.java
- (조준범이) 구현한 엔티티들에 대해 연관관계가 있다면 모두 지연로딩을 적용함
- 필요한 리포지토리 메서드의 경우 페치조인을 적용함
- 온보딩API를 만들며 깨졌던 테스트코드 수정 및 온보딩API 테스트 코드 작성 
- 지각히스토리 조회 API 성능 추가 개선
[성능 개선 전]
[성능 개선 후]
**668ms -> 542ms** 로 약간의 성능개선
[성능 개선 방법]
- Scheudle엔티티에 user_id 인덱스, latnessTime 인덱스 생성
- 지각히스토리조회메서드에 (페치)조인 제거
(지각히스토리 조회 API 성능 개선을 위해 페치조인을 했었는데 해당
메서드를 사용하는 서비스메서드에서 USER를 참조하지 않아서 페치조인을
할 필요가 없다고 판단해 쿼리 수정함.)
- 제가 구현하지 않은 API에 대해서는 아직 성능 개선 작업 진행하지 않았습니다!
> [mod] 지각히스토리 조회 API 성능 추가개선 / 연관관계에 지연로딩 세팅 및 필요시 페치조인 적용 / 테스트 코드 수정

- ontime-back/src/main/java/devkor/ontime_back/applelogin/AppleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/applelogin/ApplePublicKey.java
- ontime-back/src/main/java/devkor/ontime_back/applelogin/ApplePublicKeyGenerator.java
- ontime-back/src/main/java/devkor/ontime_back/applelogin/ApplePublicKeyResponse.java
- ontime-back/src/main/java/devkor/ontime_back/applelogin/AppleTokenResponse.java
- ontime-back/src/main/java/devkor/ontime_back/controller/SocialAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthAppleLoginRequestDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthAppleUserDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/SocialType.java
- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtUtils.java
**Identity token**
- ID 토큰 검증을 통해 얻는 사용자 정보 
- ID 토큰을 검증하기 위해 수행할 작업
1. 토큰을 앱 서버로 안전하게 전송
- 모바일 앱(네이티브) 또는 웹 앱에서 Apple 로그인 후, 서버로 ID 토큰을 전달
2. JWT(JSON Web Token) 서명 검증
- Apple 서버의 공개 키(Public Key) 를 사용하여 서명을 검증
- Apple은 JWS E256 알고리즘을 사용하여 서명
3. Nonce 검증
- 요청할 때 사용한 nonce 값을 검증하여 재사용 공격(Replay Attack) 을 방지
4. 토큰 필드 값 검증
- iss(발급자) 값이 https://appleid.apple.com/ 인지 확인
- aud(대상자) 값이 개발자 계정의 client_id 와 일치하는지 확인
- 현재 시간이 exp(토큰 만료 시간)보다 이전인지 확인
**Authorization Code**
- apple server에서 제공하는 accesstoken, refreshtoken 발급받을때 필요
- 애플로그인 철회 감지를 위해 refreshtoken을 통해 확인
**추가한 Controller**
POST /apple/registerOrLogin
Request Body: 
{
"idToken" : "dsafsdfa", 
"authCode" : "sdafsdfa",
"fullName" : "name"
}
**프론트측과 확인해야할 부분**
- idToken, authCode와 최초 로그인시 전달되는 fullName을 프론트측으로부터 받아야함
- idToken, authCode는 …
> [Feat] 애플로그인 기능 추가

- ontime-back/src/main/java/devkor/ontime_back/global/generallogin/handler/LoginSuccessHandler.java
application.properties의 apple.id를 진서님에게 받지 못해
camalcase로 여유시간이 반환되는지는 체크하지 못하였으나
수정한 코드가 한 단어 수준이므로 99% 작동할 것 같습니다.
> [mod] 로그인시 반환되는 spareTime변수 camal case로 수정

- ontime-back/src/main/java/devkor/ontime_back/controller/SocialAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthAppleRequestDto.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/apple/AppleLoginFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/apple/AppleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
revokeToken을 위해,
애플 로그인: https://appleid.apple.com/auth/revoke 주소로 refreshToken 전달
구글 로그인: https://oauth2.googleapis.com/revoke? 주소로 refreshToken 전달
-> 서비스내에서는 서비스 자체 jwt를 사용할 예정이라 
이를 위해서 각 인증서버에서 제공하는 refreshToken을 따로 db에 저장하고 있어야함.
User entity에 socialLoginToken을 추가하고
회원탈퇴를 할 경우, user accesstoken을 통해 socialLoginToken을 불러온 후, revokeToken 진행 후 db에서 사용자 삭제함.
애플로그인 회원탈퇴 (완), 구글로그인은 프론트측에서 refreshToken을 받은 후 다시 테스트 예정
> [Feat] 애플로그인 회원탈퇴 구현

- ontime-back/src/main/java/devkor/ontime_back/global/generallogin/handler/LoginSuccessHandler.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/apple/AppleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
- **LoginSuccessHandler**, **AppleLoginService**, **GoogleLoginService**의 로그인 시 note값이 null일 때 반환되는 형식을 수정하였음.
- 출력결과를 다음과 같이 변경 (**"null" -> nul**l)
> [mod] 로그인시 note값이 null일 때 반환되는 형식 수정("null" -> null)

- ontime-back/src/main/java/devkor/ontime_back/repository/PreparationUserRepository.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- 유저 하드삭제 시 준비과정의 nextPreparation필드 null로 초기화 하고 cascade삭제되게 설정하였음.
(프로덕션 서버에서 유저 하드삭제시 nextPreparation필드가 외래키 제한조건에 걸려 preparatiob_user데이터가 삭제되지 않아 오류가 발생했었음)
- 프로덕션 서버에서 테스트를 해본 것은 아니여서 프로덕션 서버에서 동작한다는 보장이 없음.
- 개발서버에서는 코드 수정전에도 동작한 것으로 보아, 프로덕션서버와 개발서버간의 db설정에 차이가 있다거나 하는 가능성이 있어 차후 확인해봐야할 것 같음.
> [mod] 유저 하드삭제시 준비과정의 nextPreparation필드 null로 초기화 하고 cascade삭제되게 설정

- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- **(수정 전)** 유저삭제API호출 시 유저를 삭제하는 메서드를 실행시키기 전 유저준비과정의 nextPreparation필드를 모두 NULL로 초기화 한 뒤 유저 삭제 메서드를 실행했음.
- **(수정 후)** 위 코드를 삭제하고, **DB에 CASCADE옵션**을 넣어서 자동삭제되게 설정. 
(유저 준비과정뿐만 아니라 약속 준비과정에도 CASCADE 옵션 넣었음. schedule삭제할 때 약속준비과정이 schedule참조하고 있어서 schedule이 삭제가 안되는 오류가 발생했었음.)
- 기존 방법은 스프링 서버에서 DB 서버로 **여러번의 쿼리**를 날려야했음.
- 수정 후의 방법은 **한방의 쿼리**가 날아가고 DB에서 연관된 테이블을 모두 삭제시키기 때문에 **성능적으로 더 우수**함.
- 트러블 슈팅을 하면서 운영서버의 application.properties를 확인하였는데 spring-ddl-auto 옵션이 update로 돼있는 것을 확인할 수 있었음. 운영서버에서 해당 옵션을 update로 설정하는 것은 지양해야함. (예: 기존에 데이터가 있는 테이블에 not null인 필드를 추가하면, 기존 데이터가 삽입이 안되는 치명적 오류가 발생할 수 있음) 
- 따라서 **ddl-auto 옵션을 update -> validate로 변경**하는 것을 제안드립니다.
- (References) 
https://colabear754.tistory.com/136#update
https://smpark1020.tistory.com/140 …
> [mod] 유저 삭제시 유저준비과정 데이터 삭제방법 변경

- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationSchedule.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationScheduleService.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- PreparationSchedule엔티티의 필드 preparationId -> preparationScheduleId으로 수정
- PreparationSchedule엔티티의 필드 nextPreparation @ManyToOne -> @OneToOne으로 수정
- PreparationScheduleService 클래스에 Transactional(ReadOnly=True)걸고, 내부 메서드 중 CUD가 필요한 메서드에 Transactional을 추가로 걸었음
- PreparationSchedule 조회 API를 만들다 80%이상 완성하고 호출URL 네이밍하는 와중 Swagger확인하면서 해당API가 이미 존재하는 것을 확인하였습니다.
- 따라서 작업한 내용 전부 없애고 작업 도중 수행한 리팩토링만 PUSH합니다.
close #98
> [mod] PreparationSchedule 엔티티 필드명 및 연관관계 수정, @Transactional

- ontime-back/src/main/java/devkor/ontime_back/controller/PreparationUserController.java
- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationSchedule.java
- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationUser.java
- ontime-back/src/main/java/devkor/ontime_back/repository/PreparationScheduleRepository.java
- ontime-back/src/main/java/devkor/ontime_back/repository/PreparationUserRepository.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationScheduleService.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationUserService.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- preparationSchedule: @ManyToOne 관계인 schedule과 @OneToOne 관계인 nextPreparation에 `(fetch = FetchType.LAZY)` 설정 적용
- preparationUser: @ManyToOne 관계인 user와 @OneToOne 관계인 nextPreparation에 `(fetch = FetchType.LAZY)` 설정 적용
- `findByScheduleWithNextPreparation`, `findByUserIdWithNextPreparation`, `findFirstPreparationUserByUserIdWithNextPreparation` 메서드에서 한 번의 쿼리로 PreparationSchedule과 nextPreparation을 함께 로딩하여 성능을 최적화
- 각종 예외 메시지 한글로 수정
- Hibernate는 프록시 객체를 만들 때 연관된 객체가 없을 수 있다는 점을 고려
- `@ManyToOne`, `@OneToMany` - 연관된 객체가 없는 경우라도 “컬렉션(empty collection)“이라는 빈 객체가 명확히 존재
-> 별도 쿼리를 하지 않고 지연로딩 프록시를 쉽게 만듦
- `@OneToOne` 관계 - 연관된 객체가 없으면 NULL
-> NULL 여부를 알기 위해 추가 SELECT 쿼리를 즉시 실행할 가능성 존재
- @ManyToOne - 연관된 엔티티의 ID가 존재하므로, JPA는 이 ID를 이용해서 프록시 객체를 만들 수 있음
- @OneToOne - FK가 있는 주 엔티티는 Lazy Loading이 가능, FK가 …
> [Mod] preparation 조회 API 및 preparation 관련 메서드 성능 개선

- ontime-back/src/test/java/devkor/ontime_back/ControllerTestSupport.java
- ontime-back/src/test/java/devkor/ontime_back/controller/PreparationUserControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/ScheduleControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/PreparationUserServiceTest.java
- 리팩토링 과정에서 통일한 getUserIdFromToken를 모두 userAuthService에서 불러오도록 수정
- Controller 테스트 - API 응답을 검증하는 것이 목적 -> Mocking을 활용하여 ScheduleService의 의존성을 제거
- Service 테스트 - 실제 데이터 저장 및 조회가 필요한 로직 -> DB를 사용하여 검증
- Mockito.verify()를 활용하여 서비스 메서드가 기대한 횟수만큼 호출되었는지 검증
- PreparationUserControllerTest 파일 설정을 위해 ControllerTestSupport 설정 추가 
close #102
> [Mod] preparationUser api 테스트코드 작성

- ontime-back/build.gradle
- ontime-back/docker-compose.yml
- ontime-back/src/main/resources/db/migration/V1__init.sql
- `build.gradle` - `implementation 'org.flywaydb:flyway-mysql'` 추가
- `V1__init.sql` - 기존에 JPA를 사용하여 엔티티가 자동으로 데이터베이스에 생성되었던 부분을 SQL 스크립트를 직접 작성하여 테이블을 생성
- `docker-compose.yml` - mysql-container와의 연결 부분 삭제
- 데이터베이스 변경을 체계적으로 관리하고, 안정성을 유지하면서 운영 환경에 반영
- 스프링부트가 지원하는 마이그레이션 툴 : (대표적) flyway + liquibase
- 주로 SQL을 사용할 것 같아, JSON, YAML 등을 제공하는 추상화를 누릴 수 있는 Liquibase가 매력적이지 않음
- Flyway가 공식 문서가 좀 더 상세히 작성 + 레퍼런스가 더 많음
- 데이터베이스 버전 관리
- 자동 마이그레이션 수행
- 여러 환경(로컬, 개발, 운영)에서 동일한 스키마 유지
1. flyway_schema_history 테이블 생성 - 마이그레이션 이력 저장
2. SQL 마이그레이션 파일 실행 
3. 실행된 마이그레이션은 flyway_schema_history에 기록
4. 새로운 SQL 스크립트가 추가되면 이전 기록과 비교하여 적용되지 않은 것만 실행
(마이그레이션 파일은 DB 변경이 필요할 때마다 개발자가 직접 SQL 파일을 작성)
간단히 요약하자면, sql 마이그레이션 파일로 db를 **형상 관리**하고 `spring.jpa.hibernate.ddl-auto=validate` 옵션을 활용한 **검증**을 하도록 설정하였습니다.
> [Feat&Mod] flyway 세팅 및 docker-compose 파일 수정

- ontime-back/docker-compose.yml
- ontime-container에서 depends on으로 mysql-container 연결해놓았던 설정을 제거
- depends-on: Docker Compose에서 컨테이너 간의 의존성을 설정 (원래는 mysql-container를 사용했기 때문에 ontime-container와 의존성 설정을 해놓았는데 mysql-container를 삭제하면서 의존성도 제거)
> [Mod] docker-compose 파일 수정 

- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtAuthenticationFilter.java
- NO_CHECK_URLS에 /swagger관련 주소와 /sign-up 추가
swagger와 sign-up 접근이 안됨
.permitAll() 설정은 Security 인증을 허용하지만, JwtAuthenticationFilter는 그대로 실행됨. JwtAuthenticationFilter에서 accessToken == null && refreshToken == null이면 요청이 컨트롤러까지 가지 않고 필터 체인에서 종료됨.
(Security에서 허용하더라도 JwtAuthenticationFilter가 먼저 실행되면 요청이 거부될 수 있음.)
기존 코드에서는 accesstoken, refreshtoken 둘다 없을때 if (refreshToken == null) 를 통과하면서 checkAccessTokenAndAuthentication()가 실행되면서 JWT 없이도 filterChain.doFilter()가 호출되어 요청이 컨트롤러까지 도달했음.
NO_CHECK_URLS에 /swagger관련 주소와 /sign-up 추가하여 JwtAuthenticationFilter를 통과하지 않도록 설정
- .permitAll() 설정은 Security 인증을 허용하지만, JwtAuthenticationFilter는 그대로 실행됨. Security 인증은 컨트롤러에서 적용됨 
- Security의 인증 흐름
- Http 요청 → JwtAuthenticationFilter가 실행됨.
- (NO_CHECK_URLS에 포함된 경우, 필터를 건너뛰고 Security까지 요청이 전달됨.)
- Security에서 …
> [Mod] NO_CHECK_URLS 추가

- ontime-back/src/main/java/devkor/ontime_back/controller/PreparationScheduleController.java
- ontime-back/src/test/java/devkor/ontime_back/ControllerTestSupport.java
- ontime-back/src/test/java/devkor/ontime_back/controller/PreparationScheduleControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/PreparationScheduleServiceTest.java
- Controller 테스트 - API 응답을 검증
- Service 테스트 - 실제 데이터 저장 및 조회를 DB를 사용하여 검증
- PreparationScheduleControllerTest 파일 설정을 위해 ControllerTestSupport 설정 추가
- PreparationScheduleController에 있는 modifyPreparationSchedule 메서드명 수정
> [Mod] preparationSchedule api 테스트코드 작성

- ontime-back/src/main/java/devkor/ontime_back/config/SecurityConfig.java
- Authorization, Authorization-refresh 헤더 관련해서 setExposedHeaders 설정 추가
**문제) Authorization 헤더를 클라이언트에서 받을 수 없음**
- 브라우저의 보안 정책으로 인해 Authorization, Set-Cookie, WWW-Authenticate 같은 민감한 헤더는 기본적으로 숨겨짐
**해결방법) setExposedHeaders를 사용**
- 클라이언트(프론트엔드)에서 Authorization, Authorization-refresh 헤더에 접근할 수 있도록 허용
변경 전
변경 후
요청 자체는 인증이 없어서 401 Unauthorized로 거부되었지만 CORS 헤더는 응답에 포함되어서 CORS 설정이 적용되고 있음을 확인가능합니다. 변경 후에는 Access-Control-Expose-Headers 포함되어 클라이언트가 접근 가능함을 확인할 수 있습니다.
> [Mod] setExposedHeaders 설정 추가

- ontime-back/src/main/java/devkor/ontime_back/LoggingAspect.java
- ontime-back/src/main/java/devkor/ontime_back/response/ErrorCode.java
- ontime-back/src/main/java/devkor/ontime_back/response/GlobalExceptionHandler.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationScheduleService.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationUserService.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- ontime-back/src/test/java/devkor/ontime_back/service/PreparationScheduleServiceTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/PreparationUserServiceTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/ScheduleServiceTest.java
- `ErrorCode`: 비즈니스로직 에러메시지 수정
- `LoggingAspect`: errorlog에 `GeneralException`의 `exceptionName`으로 수정
- `GlobalExceptionHandler`: Dto에 잘못된 데이터타입으로 데이터가 들어온 경우 발생하는 `HttpMessageNotReadableException` 다루는 `exceptionhandler` 추가
- `PreparationScheduleService`, `PreparationUserService`, `ScheduleService`: `EntityNotFoundException`, `AccessDeniedException`와 같은 Exception을 `GeneralException`으로 처리 (Api 응답 통일 및 비즈니스 로직에서 발생하는 예외는 generalException으로 처리하는 것이 적절)
- `PreparationScheduleServiceTest`, `PreparationUserServiceTest`, `ScheduleServiceTest`: Exception 처리 부분 수정
---
- 특정 api로 요청하고 `GeneralException`에서 처리하지않는 예외가 발생할시, apiLog에서 `request.getRequestURI()`가 `/error`로 저장됨
- apiLog를 저장할 때, requestUrl이 `/error`로 나와 어느 api에서 에러가 발생한지 확인이 어려움
- Spring Boot에서는 내부적으로 Internal Server Error가 발생하면 요청 URL이 …
> [Mod] Error log 처리 방식 수정

- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthGoogleRequestDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthGoogleUserDto.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/apple/AppleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
- appleLoginService - userSettingId 저장 추가, Claim에서 exp 확인 추가
- OAuthGoogleUserDto - 사용하지 않는 정보 삭제
- OAuthGoogleRequestDto - accessToken이 아닌 idToken으로 수정
- GoogleLoginService - userSettingId 저장 추가, google idToken 인증 추가
- GoogleLoginFilter - idToken 인증 추가에 따른 코드 수정
**ID Token / Access Token**
- ID Token:  로그인 인증과 같이 사용자의 신원을 확인, Access Token: 특정 리소스(API)에 접근
- 자체서비스 JWT를 발급하기 때문에 구글 소셜로그인을 구현할때는 사용자가 정상적으로 로그인했는지를 검증할 수 있는 ID Token을 통해 인증을 받는 방법이 더 적합
---
**idtoken을 검증하기 위해 GoogleIdTokenVerifier 사용**
- GoogleIdTokenVerifier의 verify(identityToken)
```
public boolean verify(GoogleIdToken googleIdToken) throws GeneralSecurityException, IOException {
if (!super.verifyPayload(googleIdToken)) {
return false;
} else {
// Google 공개 키 가져옴
Iterator var2 = this.publicKeys.getPublicKeys().iterator(); …
```
> [Mod] google 로그인 요청을 idtoken로 수정

- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserSignUpDto.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserAuthControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/UserAuthServiceTest.java
- 일반 회원가입 시에도 UUID를 서버에서 생성하는 것으로 수정하였음
- 회원가입 코드 리팩토링을 진행하였음
- (변경 전) 서비스계층에서 User 객체를 반환해 컨트롤러 계층에서 이를 Dto로 변환해서 반환했음
(변경 후) 서비스계층에서 Dto를 만들어서 반환하고 컨트롤러는 받아서 그대로 반환
- (변경 전) 서비스계층의 회원가입 코드가 내부메서드 없이 길게 전개됐음
(변경 후) private 내부 메서드를 사용해 가독성을 높임 
- 변경에 따라 테스트코드, Swagger 명세 수정하였음
Closed #186 
Closed #187
> [mod&refact] 일반회원가입시 UUID 서버에서 생성하는 것으로 수정 및 회원가입코드 리팩토링

- .idea/dataSources.xml
- .idea/modules/devkor.ontime-back.main.iml
- .idea/modules/ontime-back.main.iml
- .idea/sqlDataSources.xml
- ontime-back/src/main/java/devkor/ontime_back/config/SchedulerConfig.java
- ontime-back/src/main/java/devkor/ontime_back/config/SwaggerConfig.java
- ontime-back/src/main/java/devkor/ontime_back/entity/NotificationSchedule.java
- ontime-back/src/main/java/devkor/ontime_back/repository/NotificationScheduleRepository.java
- ontime-back/src/main/java/devkor/ontime_back/response/ErrorCode.java
- ontime-back/src/main/java/devkor/ontime_back/scheduler/NotificationScheduler.java
- ontime-back/src/main/java/devkor/ontime_back/service/NotificationRecoveryService.java
- ontime-back/src/main/java/devkor/ontime_back/service/NotificationService.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- ontime-back/src/main/resources/db/migration/V2__create_notification_schedule.sql
- ontime-back/src/test/java/devkor/ontime_back/service/ScheduleServiceTest.java
기존에는 매 분마다 
`Select * from schedule where time=현재시각+5분`
위 쿼리를 실행 해 모든 약속을 순회하며 5분뒤의 약속을 조회했었음.
즉, 약속이 없는 시각에도 불필요하게 스케줄링 작업을 실행하여 메모리를 낭비했었음.
따라서 약속 생성 시점에 알림을 동적으로 등록하여 이후에는 따로 약속을 스캔할 필요 없이 스케줄링이 되게 로직을 변경하였고, 그 과정에서 알림테이블 생성, 비동기 처리 등 최적화 작업을 진행하였음.
- 알림을 동적으로 스케줄링
- (변경 전) @Scheduled 애너테이션을 활용해 매분마다 모든 약속을 스캔하여 알림 푸시
- (변경 후) 약속 생성할 때 TaskScheduler를 이용해 알림스케줄링계획을 동적으로 등록해 TaskScheduler가 해당 시각이 되면 자동으로 알림 푸시
- 불필요한 메모리 낭비, 데이터 스캔이 줄어듦
- NotificationSchedule 테이블 생성
- TaskScheduler를 통해 동적으로 등록된 알림스케줄은 WAS가 재시작되면 정보가 소실됨. 따라서 WAS가 재시작됐을 때 DB에서 등록된 알림정보를 불러오기 위해 NotificationSchedule 테이블을 생성하였음.
- 이 때 서버 재시작시 불러온 NotificationSchedule 데이터에 Schedule이 LazyLoading설정 돼있어, LazyInitializationException이 발생할 수 있어 페치조인으로 방지하였음.
- TaskScheduler에는 알림스케줄이 Map형태로 저장됨.
- 약속을 수정하거나 삭제하면 동적으로 등록됐던 스케줄을 …
> [Refact] 알림 스케줄러 로직 변경 및 최적화

- ontime-back/src/main/java/devkor/ontime_back/entity/DoneStatus.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/resources/db/migration/V3__add_is_done_to_schedule.sql
- 비정상 종료 처리를 위해서 doneStatus 컬럼 추가
- PUT /schedules/{scheduleId}/finish 로 latenesstime을 받을때, 아래와 같이 doneStatus에 저장됨
```
LATE        // 지각종료 - latenesstime > 0
NORMAL      // 지각 안 한 종료 - latenesstime = 0
ABNORMAL    // 비정상종료 - latenesstime = -2
NOT_ENDED    // 종료되지 않음 - latenesstime = -1
```
> [Feat] doneStatus 컬럼 추가

- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtAuthenticationFilter.java
- 재발급 시에 User테이블의 AccessToken필드 업데이트되게하여 문제 해결함
> [Fix] 재발급된 엑세스토큰 권한 통과 못하는 에러 수정
