DevKor-github/OnTime-back

- ontime-back/src/main/java/devkor/ontime_back/entity/Place.java
- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationSchedule.java
- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationUser.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
> [feature] entity 구현

- ontime-back/.gitignore
- ontime-back/src/main/java/devkor/ontime_back/config/SecurityConfig.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserAdditionalInfoDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
> [feat]일반회원가입 후 추가 정보 기입 기능 구현

- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleModDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Place.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
schedule add 기능만 우선적으로 수정했습니다 ~
> mod::place uuid 관련 기능 수정

- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/LatenessHistoryResponse.java
- ontime-back/src/main/java/devkor/ontime_back/dto/PunctualityPageResponse.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleHistoryResponse.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/repository/ScheduleRepository.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
- 성실도 페이지 GET 기능 구현
- 성실도 초기화 기능 구현
> [feat] 성실도 관련 기능 구현

- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdatePunctualityScoreDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
- User엔티티에 속성 추가 for 성실도 계산
- 성실도 초기화 로직 수정
- 약속 준비 종료 시 성실도 점수 업데이트 기능 구현
> [Mod] 성실도 관련 기능 수정

- ontime-back/Dockerfile
- ontime-back/docker-compose.yml
- ontime-back/src/main/java/devkor/ontime_back/dto/SocialUserSignupDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/service/OAuth2Service.java
1. pull 받은 후,
2. Ontime-back/src/main/resources/application.properties 추가
3. docker-compose.yml파일에 PASSWORD부분이 삭제 되어있는 상태로 비밀번호 입력
4. 해당 폴더 위치로 이동 후, docker-compose up --build -d로 실행
Docker 명령어
컨테이너 시작: docker-compose up -d
실행 로그 확인: docker-compose logs -f
컨테이너 중지: docker-compose down
다시 빌드 후 시작: docker-compose up --build -d
> [Feat] Docker 파일 설정

- ontime-back/src/main/java/devkor/ontime_back/config/SwaggerConfig.java
swagger에 헤더 accesstoken 추가를 위해 설정하였습니다.
> [Mod] swagger 전역 헤더정보 관리 설정

- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleModDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/controller/OAuth2Controller.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
schedule 관련 기능 swagger 설정 완료했습니다
> [Mod] swagger schedule 설정 완료

- ontime-back/src/main/java/devkor/ontime_back/controller/DocumentController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/FeedbackController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserSettingController.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Feedback.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Friend.java
- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationUser.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
- ontime-back/src/main/java/devkor/ontime_back/entity/UserSetting.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
- UserAuthController, UserController, UserSettingController, ScheduleController, FeedbackController, DocumentController Swagger API 명세 완료
> [mod] Swagger 명세 완료

- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtAuthenticationFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtTokenProvider.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/handler/OAuth2LoginSuccessHandler.java
Authorization-refresh 로 refreshtoken 넣으면 되도록 수정해놓았습니다.
> [Mod] jwt refreshtoken header 설정 변경

- ontime-back/src/main/java/devkor/ontime_back/config/SwaggerConfig.java
- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtAuthenticationFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtTokenProvider.java
1. JwtAuthenticationFilter에 필터 중복 수행되게 하는 코드 삭제.
2. FE와의 원할한 협업을 위해 Swagger에 JWT 인증 과정 명세
3. 엑세스토큰 만료기간 수정
- 10초 -> 1시간
> [Mod] 필터오류 수정 및 JWT설정, 명세

- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/response/ApiResponseForm.java
- ontime-back/src/main/java/devkor/ontime_back/response/ErrorCode.java
- ontime-back/src/main/java/devkor/ontime_back/response/GeneralException.java
- ontime-back/src/main/java/devkor/ontime_back/response/GlobalExceptionHandler.java
**ApiResponse 객체를 사용해서 형식 통일**
- ErrorCode를 enum으로 정의하여 에러 코드와 메시지를 관리
- GeneralException을 커스터마이즈하여 ErrorCode를 처리
- GlobalExceptionHandler에서 예외를 처리하여 응답을 클라이언트에 반환
Post의 경우에 반환할 data가 없는 경우: 
ex) 약속 추가 api 코드 확인 (/schedule/add)
return ResponseEntity.status(HttpStatus.OK).body(ApiResponseForm.success(null));
{
"status": "success",
"code": "200",
"message": "OK",
"data": null
}
Get의 경우에 반환할 data가 있는 경우:
ex) 전체 약속 조회 api 확인 (/schedule/show/all)
return ResponseEntity.status(HttpStatus.OK).body(ApiResponseForm.success(schedules));
{
"status": "success",
"code": "200",
"message": "OK",
"data": [
{
"scheduleId": "123e4567-e89b-12d3-a456-426614170105",
"placeName": "My home",
"scheduleName": "Family Meetings",
"moveTime": "00:20:00",
"scheduleTime": "2024-11-18T19:30:00",
"scheduleSpareTime": …
> [Feat] api respone 형식 통일

- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdateSpareTimeDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
사용자 여유시간 업데이트하는 API 구현했습니다.
UserController에 구현했습니다.
> [feat] 사용자 여유시간 업데이트 API 구현

- ontime-back/src/main/java/devkor/ontime_back/controller/DocumentController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdateSpareTimeDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
Ontime 소개글 조회 API 구현하였습니다.
DocumentController에 구현하였습니다.
> [Feat] Ontime 소개글 조회 API 구현

- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleModDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Schedule.java
schedulesparetime Time에서 Integer로 변환하고 swagger 수정하였습니다.
> [Mod] schedulesparetime integer 변환

- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ChangePasswordDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserAdditionalInfoDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserSignUpDto.java
- ontime-back/src/test/java/devkor/ontime_back/controller/ScheduleControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserAuthControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserSettingControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserSignUpTest.java
- UserAuthController, UserController, UserSettingController에 해당하는 API 테스트 코드 작성
- SignUpTest는 따로 파일을 분리하였음.
> [feat] JUnit 테스트 코드 작성

- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleDto.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
1. schedule/show/id 즉, scheduleId로 schedule 조회하는 기능 추가
2. schedule/show, schedule/show/id 기능에 Response로 Place 관련된 모든 필드 추가
> [Mod] schedule id로 조회 기능 추가 및 Response 값 수정

- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
프론트측의 요청에 따라
약속(Schedule)의 디폴트 지각시간(latenessTime) 값을 NULL에서 -1로 수정하였습니다.
> [mod] 약속의 디폴트 지각시간 값 수정(NULL -> -1)

- ontime-back/.gitignore
- ontime-back/GoogleService-Info.plist
- ontime-back/build.gradle
- ontime-back/src/main/java/devkor/ontime_back/config/FirebaseInitialization.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/NotificationService.java
- FCM에 애플 푸시 노티피케이션 키를 등록함.
- FCM에서 json, plist등을 받아 프로젝트에 추가했음.(gitignore처리해서 개인이 추가해야함)
- NotificationService의 sendNotificationToUser메서드에 FCM에 알림보내는 코드 작성함
- FE와의 테스트 필요(FE에서 FCM에 파이어베이스토큰을 발급 받아 BE로 넘겨줘야 함)
> [feat] FCM을 이용한 약속 알림 기능 구현(테스트 필요)

- ontime-back/src/main/java/devkor/ontime_back/config/FirebaseInitialization.java
- ontime-back/src/main/java/devkor/ontime_back/controller/FirebaseTokenController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/FirebaseTokenAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/response/ErrorCode.java
- ontime-back/src/main/java/devkor/ontime_back/service/FirebaseTokenService.java
FirebaseTokenController에 
1. FCM 토큰 등록 API 
2. FCM 푸시 테스트 API 
구현하였습니다.
> [feat] FCM 토큰 등록 API, 테스트 API 구현

- ontime-back/src/main/java/devkor/ontime_back/service/UserAuthService.java
UserAuthService에서 signUp메서드에 user데이터와 usersetting중 하나만 업데이트 되는 것을 방지하기 위해 트랜잭션 처리하였습니다
> [mod] 회원가입 서비스 트랜잭션 처리

- ontime-back/src/main/java/devkor/ontime_back/config/SecurityConfig.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthGoogleUserDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthKakaoUserDto.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/controller/OAuth2Controller.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/handler/OAuth2LoginSuccessHandler.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/service/OAuth2Service.java
소셜 로그인시 flutter에서 user 정보를 받아와서 jwt를 반환하는 형식으로 로직을 수정
> [Mod] social login 로직 수정

- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
여유시간 수정하는 user/update -> user/spare-time으로 이름 변경하였습니다.
> [Mod] user/spare-time 이름 변경

- ontime-back/src/main/java/devkor/ontime_back/entity/FriendShip.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/service/NotificationService.java
지난번의 push에서 Frienship엔티티가 정상적으로 추가되지 않아 다시 PR 올립니다.
> feat:: 커뮤니티 기능을 위한 Friendship 엔티티 추가(retry)

- ontime-back/src/main/java/devkor/ontime_back/LoggingAspect.java
- ontime-back/src/main/java/devkor/ontime_back/dto/FeedbackAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/FinishPreparationDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/FirebaseTokenAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/LatenessHistoryResponse.java
- ontime-back/src/main/java/devkor/ontime_back/dto/PreparationDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/PunctualityScoreResponse.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleModDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/SchedulePeriodDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/SocialUserSignupDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdatePunctualityScoreDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UpdateSpareTimeDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserAdditionalInfoDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserSettingUpdateDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserSignUpResponse.java
- ontime-back/src/main/java/devkor/ontime_back/entity/ApiLog.java
- ontime-back/src/main/java/devkor/ontime_back/repository/ApiLogRepository.java
- requestUrl, requestMethod, userId, clientIp responseStatus, takenTime, createdAt를 ApiLog로 데이터베이스에 저장
- LogRequest) requestUrl, requestMethod, userId, clientIp responseStatus, takenTime, createdAt + pathVariable, requestBody 가 로그로 출력
- LogException) requestUrl, requestMethod, userId, clientIp responseStatus, takenTime, createdAt + exceptionName, exceptionMessage 가 로그로 출력
> [Feat] LoggingAspect 추가 및 AOP 기반 로깅 구현

- ontime-back/src/main/java/devkor/ontime_back/entity/FriendShip.java
- ontime-back/src/main/java/devkor/ontime_back/repository/FriendshipRepository.java
- ontime-back/src/main/java/devkor/ontime_back/service/FriendshipService.java
- ontime-back/src/test/java/devkor/ontime_back/service/FriendshipServiceTest.java
- **친구 추가 링크 생성 및 반환 API** 서비스&리포지토리 계층 코드 및 테스트코드 작성 완료
- **친구추가 페이지 반환 API** 서비스&리포지토리 계층 코드 및 테스트코드 작성 완료
- **친구추가 수락상태 업데이트 API** 서비스&리포지토리 계층 코드 및 테스트코드 작성 완료
- **친구목록 조회 API** 서비스&리포지토리 계층 코드 및 테스트코드 작성 완료
- **TDD(Test Driven Development)** 개발 방식으로 코드 작성하여 테스트 코드를 먼저 작성하고 프로덕션 코드를 작성해(RED-GREEN-REFACTOR) **엣지 케이스**를 충분히 고려하여 작성하였음.
- **API 명세** 및 FE와 맞춰야할 부분은 컨트롤러 계층 코드 작성이 완료되면 **해당 PR에 내용 작성할 예정**
- 59번PR에서 발생한 이슈와 동일한 이슈로, **테스트코드에서 빌더패턴으로 하드저장한 객체**는 **영속성 컨텍스트**에 들어가지 않으므로 테스트코드에서 해당 객체의 값의 변경을 확인하고 싶으면 findbyId등의 메서드를 통해 **영속성 컨텍스트에서 관리되는 객체의 복사본**으로 값의 변경을 확인해야한다. 
(하드저장한 객체에서 getId() 등을 하면 업데이트된 값이 아니라 기존 하드 저장한 값이 반환됨. 따라서 findbyId를 통해 updatedUser와 같은 새 객체를 생성하고 할당한 뒤 변경값을 조회해야 함.)
[Test Results — ontime-back [test].pdf](https://github.com/user-attachments/files/18557304/Tes …
> [feat] TDD개발방식으로 친구추가 API의 서비스&리포지토리 계층 구현 완료

- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserSignUpResponse.java
- ontime-back/src/main/java/devkor/ontime_back/global/generallogin/handler/LoginSuccessHandler.java
- 일반로그인, 일반회원가입 요청 반환시 Jsend형식으로 반환되게 수정
- FE분들의 요청으로 코드 수정하였습니다.
- 아직 스웨거로 반환값 명세하는 것은 하지 않았으니 참고바랍니다.
[일반 회원가입 반환결과]
[일반로그인 반환결과]
> [mod] 일반로그인, 일반회원가입 요청 반환 시 Jsend형식으로 반환되게 수정

- ontime-back/src/main/java/devkor/ontime_back/global/oauth/filter/GoogleLoginFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/filter/KakaoLoginFilter.java
일반로그인과 같은 형식으로 나오도록 응답 수정했습니다.
> [Mod] 소셜로그인 응답 수정

- ontime-back/docker-compose.yml
- ontime-back/src/main/java/devkor/ontime_back/config/SecurityConfig.java
- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthGoogleRequestDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/global/generallogin/handler/LoginSuccessHandler.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/apple/AppleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
소셜로그인 response 형식 수정 및 header에 refreshtoken 반환 추가하였습니다
> [Feat] 소셜로그인 response 형식 수정

- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/UserInfoResponse.java
- ontime-back/src/main/java/devkor/ontime_back/global/generallogin/handler/LoginSuccessHandler.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/apple/AppleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
- ontime-back/src/main/java/devkor/ontime_back/service/UserService.java
- UserController, UserSerivce에 사용자 정보 조회 API 구현하였음
- 엑세스토큰을 바탕으로 유저정보를 반환하는 API임
- 본 API를 구현하면서 userSignUpResponse를 재활용하기 위해 userSignUpResponse ->
userInfoResponse로 파일명을 변경하였음
> [feat] 사용자 정보 조회 API 구현

- ontime-back/src/main/java/devkor/ontime_back/dto/OAuthGoogleUserDto.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginFilter.java
- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
구글 로그인 진행할때 토큰을 통해 사용자 정보를 받아오는 과정에서 sub이 아니라 id로 필드명 수정하였습니다
> [Mod] 구글로그인시 받아오는 정보 id로 변경

- README.md
"유저 삭제시 유저준비과정 데이터 삭제방법 변경"(PR#94)를 서버에 반영하기 위한 머지입니다.
> [Merge] main to deploy

- ontime-back/build.gradle
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleAddDto.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleModDto.java
- ontime-back/src/main/java/devkor/ontime_back/entity/Place.java
- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/java/devkor/ontime_back/repository/ScheduleRepository.java
- ontime-back/src/test/java/devkor/ontime_back/controller/ScheduleControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/ScheduleServiceTest.java
- ScheduleService, ScheduleController 관련 테스트코드 작성
- Controller 테스트 - API 응답을 검증하는 것이 목적 -> **Mocking**을 활용하여 ScheduleService의 의존성을 제거
- Service 테스트 - 실제 데이터 저장 및 조회가 필요한 로직 -> **인메모리 DB**(H2)를 사용하여 검증
- Mockito.verify()를 활용하여 서비스 메서드가 기대한 횟수만큼 호출되었는지 검증
close #101
> [Mod] schedule api 테스트코드 작성

- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- final 필드가 없기 때문에 @RequiredArgsConstructor를 삭제하였습니다.
> [Mod] requiredArgsConstructor 제거

- ontime-back/src/test/java/devkor/ontime_back/service/ScheduleServiceTest.java
- 테스트코드를 일부러 실패하게 수정한 뒤 생성한 PR입니다. 
- 테스트코드 검증 파이프라인에서 테스트코드 실패를 검증해, PR을 CLOSE하고 오류검증 COMMENT가 자동으로 달리는지 확인하는 테스트용 PR입니다.
> test:: 테스트코드 검증 파이프라인(test.yml)이 작동하는지 테스트하는 테스트용 PR (5)

- ontime-back/src/main/java/devkor/ontime_back/entity/PreparationSchedule.java
- ontime-back/src/main/java/devkor/ontime_back/service/FriendshipService.java
- ontime-back/src/main/resources/db/migration/V2__schema_modifications.sql
- ontime-back/src/test/java/devkor/ontime_back/service/FriendshipServiceTest.java
- 마이그레이션 파일로 db 수정 (not null, unique, varchar 크기 수정)
- friendshipservice 테스트코드 수정
> [Mod] FriendshipService 테스트코드 수정 및 db 제약조건 수정

- ontime-back/.gitignore
- ontime-back/build.gradle
- ontime-back/src/main/java/devkor/ontime_back/config/FirebaseInitialization.java
firebase 인증용 json파일 변경에 따른 json관련 코드 변경
- build.gradle 파일 변경돼 gradle 동기화 한 번 하셔야합니다
- 개인적으로 전달드린 json파일 main/resource 아래에 저장해주시면 됩니다
> [mod] firebase 프로젝트 변경에 따른 환경값 변경

- ontime-back/Dockerfile
> [Mod] Debian 기반으로 dockerfile 수정

- ontime-back/src/main/java/devkor/ontime_back/global/oauth/google/GoogleLoginService.java
- 회원가입시 "회원가입을 성공하였습니다."라는 메시지 반환
- refreshtoken도 함께 반환
> [Mod] 회원가입 응답 수정 및 refreshtoken 반환

- ontime-back/src/main/java/devkor/ontime_back/config/SecurityConfig.java
- ontime-back/src/main/java/devkor/ontime_back/config/SwaggerConfig.java
- ontime-back/src/main/java/devkor/ontime_back/controller/DocumentController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/FeedbackController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/FirebaseTokenController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/FriendShipController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/PreparationScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/PreparationUserController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/SocialAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserAuthController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserController.java
- ontime-back/src/main/java/devkor/ontime_back/controller/UserSettingController.java
- ontime-back/src/main/java/devkor/ontime_back/dto/ScheduleModDto.java
- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtAuthenticationFilter.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- ontime-back/src/test/java/devkor/ontime_back/controller/FriendShipControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/PreparationScheduleControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/PreparationUserControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/ScheduleControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserAuthControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/controller/UserControllerTest.java
- ontime-back/src/test/java/devkor/ontime_back/service/ScheduleServiceTest.java
- 요청 엔드포인트 RESTful하게 수정하였습니다.
- 약속 준비 종료 API의 엔드포인트도 RESTful하게 수정하였습니다.
- 테스트코드도 변경한 엔드포인트에 맞게 수정하였습니다.
Closed #197
Closed #201 
Closed #196
> [Mod] 요청 엔드포인트 RESTFul하게 수정

- ontime-back/src/main/java/devkor/ontime_back/config/SwaggerConfig.java
- ontime-back/src/main/java/devkor/ontime_back/controller/ScheduleController.java
- ontime-back/src/test/java/devkor/ontime_back/controller/ScheduleControllerTest.java
- swaggerconfig에서 주석처리 되어있던 부분 주석 제거 -> server url 고정
- 엔드포인트 preparations로 통일
> [Mod] swaggerconfig 및 엔드포인트 수정

- ontime-back/src/main/java/devkor/ontime_back/entity/NotificationSchedule.java
- ontime-back/src/main/java/devkor/ontime_back/service/ScheduleService.java
- 약속 알림 시간 여유시간,이동시간,준비시간 고려하여 스케줄링되게 수정하였습니다.
- 이 때 메서드 분리를 적극적으로 활용하여 가독성을 높였습니다.
- 약속 삭제시 CASCADE 옵션을 활용하여 약속알림을 명시적으로 지우지 않고 약속만 삭제해도 전부 삭제되게 하여 가독성을 높였습니다
Closed #211
> [Feat] 약속 알림 시간 여유시간,이동시간,준비시간 고려하여 스케줄링되게 수정

- ontime-back/src/main/java/devkor/ontime_back/entity/User.java
- ontime-back/src/main/resources/db/migration/V5__change_field_accesstoken_length.sql
- ontime-back/src/main/resources/db/migration/V6__change_filed_accesstoken_longtext.sql
- ontime-back/src/main/resources/db/migration/V7__change_filed_accesstoken_refreshtoken.sql
- User 테이블 AccessToken에 @Lob을 붙여 전체 토큰내용이 저장되게 수정
> [Fix] User 테이블 accessToken 저장공간 길이 연장 by @Lob

- ontime-back/src/main/java/devkor/ontime_back/global/jwt/JwtAuthenticationFilter.java
- ontime-back/src/main/java/devkor/ontime_back/repository/PreparationUserRepository.java
- ontime-back/src/main/java/devkor/ontime_back/response/ErrorCode.java
- ontime-back/src/main/java/devkor/ontime_back/service/PreparationUserService.java
> [Release] main to deploy
